- name: Iniciar la aplicación Flask
  hosts: nodo1
  become: yes
  tasks:

  - name: Instalar Flask
    pip:
      name: flask
      state: present

- name: Iniciar la aplicación Flask
  hosts: nodo1
  become: false
  tasks:

  - name: Ejecutar la aplicación Flask
    command: python3 main.py
    async: 20
    poll: 0

  - name: Esperar a que la aplicación esté lista
    uri:
      url: "http://127.0.0.1:5010/status"
    register: response
    until: response.json.status == "READY"
    retries: 10
    delay: 1

  - name: Verificar que la aplicación está lista
    debug:
      msg: "La aplicación está lista."
